### ISSUE TITLE
Tourenplan - ovgu to matsim logic

### ISSUE THREAD

**Issue by rkoetsch** [matsim-vsp/pave#2]
Muss noch eingebaut werden in MATSim Freight language -> Tourenplan. kmt/aug19.
>> [vorhandene ovgu objekte müssen in] matsim objekte gebaut werden

//Start Element
//Pickup
//Delivery
...
//Ziel Element

**Comment by kt86** [comment]
Das hatten wir am Montag, den 16.9. gemacht.
