### ISSUE TITLE
ovgu maven jar's

### ISSUE THREAD

**Issue by rkoetsch** [matsim-vsp/pave#3]
question ... public ... https://jitpack.io/

**Comment by kt86** [comment]
Wäre sehr wichtig, weil es so ein echter Krampf ist.

In Intellij bekomme ich es gar nicht zum laufen und auch die Builds auf Travis werden immer failen, solange da diese Abhängigkeiten nicht z.B. per Maven gezogen werden können oder der Code im Repository selbst liegt.

**Comment by kt86** [comment]
Vielleicht sollte auch noch eine übergeordnete 'Pom.xml' geschaffen werden, damit man nicht alle Unterordner/Module einzeln laden muss (core, experiments,..)

**Comment by kainagel** [comment]
Ich verstehe leider nicht, wie dies hier gemeint ist.  Wenn ich dieses repo hier (matsim-vsp/pave) auschecke, dann kompiliert es nicht, weil die `ovgu.pave` Abhängigkeiten nicht aufgelöst werden.  In `pom.xml` sind diese angegeben.  Aber auf welchem repo liegen sie?  

Falls sie auf einem github repo liegen, und sie per jitpack gezogen werden sollen, dann stimmt die group-id nicht, die müsste (m.E.) so etwas wie com.github.ovgu sein.  Dort ist  aber nichts public.  Vielleicht ist dies die ursprüngliche Frage?

Falls dies die ursprüngliche Frage ist: Muss das ovgu repo denn wirklich private sein?  Bei "public" bekommen wir eine deutlich bessere Infrastruktur zur Verfügung gestellt (maven deployment, regression tests, ...).

**Comment by kt86** [comment]
Genau darum geht es. Das OVGU sollte aus us unserer (TU) Sicht public werden, damit wie via jitpack ran kommen und die gesamte Infrastruktur nutzen können.
Der Reminder dazu kam hier her, weil wir hier dann die Issues zum PAVE-Projekt pflegen.

**Comment by rkoetsch** [comment]
Sollte jetzt alles laufen.
@kt86 passt das für euch so?

**Comment by kt86** [comment]
Danke. Sieht sehr gut aus. Sowohl in IntelliJ, als auch TravisCI haben keine Probleme euren Code zu bekommen.

Mache es dann mal zu ;)
