### ISSUE TITLE
.gitignore on ovgu-repos anpassen

### ISSUE THREAD

**Issue by kt86** [matsim-vsp/pave#4]
Könntet ihr bitte .gitignore JEWEILS noch um folgende Einträge ergänzen:
/.idea/
*.iml
*.class
*.DS_Store

Ich habe es bei mir gemacht, aber kein Schreibrecht auf das Verzeichnis, weswegen ich den commit nicht pushen kann. 

Bei den Datei(typen) handelt es sich zum einen um MacOS-Spezifika (.DS_Store) bzw. zum anderen im Projektdaten von IntelliJ. Beides muss nicht in git rumgeistern.

Danke :)

**Comment by rkoetsch** [comment]
Ich denke das ist nicht mehr relevant?
