### ISSUE TITLE
Carrier(Impl) CarrierShipments & CarrierServices als Map statt Collection. 

### ISSUE THREAD

**Issue by kt86** [matsim-vsp/pave#6]
Ermöglicht das raussuchen anhand der ID, wenn man die Lösung hat und zusammen bauen möchte.

(könnte auch für MATSimJspritFactory rleevant sein, weil man dann für die Tour nicht mehr alle Shipments neu bauen muss.)

**Comment by rkoetsch** [comment]
die gleiche Frage stellt sich für CarrierVehicles ...

**Comment by kainagel** [comment]
Worauf genau bezieht sich das?

**Comment by rkoetsch** [comment]
Im Carrier (org.matsim.contrib.freight.carrier.Carrier) sind die CarrierShipments/Services/Vehicles alle als Collection definiert. Wir wollten jetzt ein Shipment/Vehicle anhand der ID rausziehen, um dem Fahrzeug eine Tour zuzuweisen bzw. dem Shipment Bearbeitungszeiten.

Das Finden anhand der ID geht aber in einer Collection nicht so einfach? Im Moment gehen wir alle durch bis das mit der richtigen ID gefunden ist.

**Comment by kainagel** [comment]
Bin einverstanden, dies durch Map<Id...,...> zu ersetzen.

LinkedHashMap als Implementation war m.E. ganz gut, und entspricht wohl auch am ehesten dem bisherigen Verhalten.

Wer macht das?

**Comment by kt86** [comment]
Änderung ist gerade in PullRequest unterwegs: matsim-org/matsim#681 .

**Comment by kt86** [comment]
Wurde mir matsim-org/matsim#681 umgesetzt und ist nun im MATSim-Snapshot

**Comment by kt86** [comment]
Anpassung hier erfolgt. Siehe #12
